# Site settings
title: Gregory Pozo
email: gregpozo24@gmail.com
url: https://kurosannin.github.io
description: "Pagina web de Gregory Pozo, dedicada a mostrar sus trabajos tecnológicos y su creatividad al mundo."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Ing. Gregory Pozo
  location: Localización
  social: En la Web
  credits: Creditos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/user/bLaCkSaNiN/videos?spfreload=10
  - title: facebook
    url: https://www.facebook.com/darkhomiez
  - title: medium
    url: https://medium.com/gregory-pozo/latest
  - title: instagram
    url: https://instagram.com/kurosannin/
  - title: github
    url: https://github.com/kurosannin
  - title: linkedin
    url: https://do.linkedin.com/pub/gregory-pozo/b4/94a/139

# Postal address (add as many lines as necessary)
address:
  - line: Vivo en un maizal
  - line: en Villa Mella, Santo Domingo,
  - line: República Dominicana.

# Credits content
credits: 'Esta página web fue creada gracias a <a href="http://github.com">Github</a> y a <a href="https://github.com/jeromelachaud"> Jerome Lachaud</a>.'

# Build settings
markdown: kramdown
permalink: pretty
